// Generated by gencpp from file cc_node/a_operation_fly_to_posRequest.msg
// DO NOT EDIT!


#ifndef CC_NODE_MESSAGE_A_OPERATION_FLY_TO_POSREQUEST_H
#define CC_NODE_MESSAGE_A_OPERATION_FLY_TO_POSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cc_node
{
template <class ContainerAllocator>
struct a_operation_fly_to_posRequest_
{
  typedef a_operation_fly_to_posRequest_<ContainerAllocator> Type;

  a_operation_fly_to_posRequest_()
    : pos_lat(0.0)
    , pos_lon(0.0)
    , pos_heading(0)
    , pos_alt(0)  {
    }
  a_operation_fly_to_posRequest_(const ContainerAllocator& _alloc)
    : pos_lat(0.0)
    , pos_lon(0.0)
    , pos_heading(0)
    , pos_alt(0)  {
  (void)_alloc;
    }



   typedef float _pos_lat_type;
  _pos_lat_type pos_lat;

   typedef float _pos_lon_type;
  _pos_lon_type pos_lon;

   typedef int32_t _pos_heading_type;
  _pos_heading_type pos_heading;

   typedef int32_t _pos_alt_type;
  _pos_alt_type pos_alt;




  typedef boost::shared_ptr< ::cc_node::a_operation_fly_to_posRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cc_node::a_operation_fly_to_posRequest_<ContainerAllocator> const> ConstPtr;

}; // struct a_operation_fly_to_posRequest_

typedef ::cc_node::a_operation_fly_to_posRequest_<std::allocator<void> > a_operation_fly_to_posRequest;

typedef boost::shared_ptr< ::cc_node::a_operation_fly_to_posRequest > a_operation_fly_to_posRequestPtr;
typedef boost::shared_ptr< ::cc_node::a_operation_fly_to_posRequest const> a_operation_fly_to_posRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cc_node::a_operation_fly_to_posRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cc_node::a_operation_fly_to_posRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cc_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cc_node::a_operation_fly_to_posRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cc_node::a_operation_fly_to_posRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cc_node::a_operation_fly_to_posRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cc_node::a_operation_fly_to_posRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cc_node::a_operation_fly_to_posRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cc_node::a_operation_fly_to_posRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cc_node::a_operation_fly_to_posRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1334cf54d53e7abe335a75dbac72c1e2";
  }

  static const char* value(const ::cc_node::a_operation_fly_to_posRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1334cf54d53e7abeULL;
  static const uint64_t static_value2 = 0x335a75dbac72c1e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::cc_node::a_operation_fly_to_posRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc_node/a_operation_fly_to_posRequest";
  }

  static const char* value(const ::cc_node::a_operation_fly_to_posRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cc_node::a_operation_fly_to_posRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pos_lat\n\
float32 pos_lon\n\
int32 pos_heading\n\
int32 pos_alt\n\
\n\
";
  }

  static const char* value(const ::cc_node::a_operation_fly_to_posRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cc_node::a_operation_fly_to_posRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos_lat);
      stream.next(m.pos_lon);
      stream.next(m.pos_heading);
      stream.next(m.pos_alt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct a_operation_fly_to_posRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cc_node::a_operation_fly_to_posRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cc_node::a_operation_fly_to_posRequest_<ContainerAllocator>& v)
  {
    s << indent << "pos_lat: ";
    Printer<float>::stream(s, indent + "  ", v.pos_lat);
    s << indent << "pos_lon: ";
    Printer<float>::stream(s, indent + "  ", v.pos_lon);
    s << indent << "pos_heading: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pos_heading);
    s << indent << "pos_alt: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pos_alt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CC_NODE_MESSAGE_A_OPERATION_FLY_TO_POSREQUEST_H
