// Generated by gencpp from file cc_node/a_operation_landing.msg
// DO NOT EDIT!


#ifndef CC_NODE_MESSAGE_A_OPERATION_LANDING_H
#define CC_NODE_MESSAGE_A_OPERATION_LANDING_H

#include <ros/service_traits.h>


#include <cc_node/a_operation_landingRequest.h>
#include <cc_node/a_operation_landingResponse.h>


namespace cc_node
{

struct a_operation_landing
{

typedef a_operation_landingRequest Request;
typedef a_operation_landingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct a_operation_landing
} // namespace cc_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cc_node::a_operation_landing > {
  static const char* value()
  {
    return "fd59bedfcc1f7eb050c1f843ac95cbaa";
  }

  static const char* value(const ::cc_node::a_operation_landing&) { return value(); }
};

template<>
struct DataType< ::cc_node::a_operation_landing > {
  static const char* value()
  {
    return "cc_node/a_operation_landing";
  }

  static const char* value(const ::cc_node::a_operation_landing&) { return value(); }
};


// service_traits::MD5Sum< ::cc_node::a_operation_landingRequest> should match 
// service_traits::MD5Sum< ::cc_node::a_operation_landing > 
template<>
struct MD5Sum< ::cc_node::a_operation_landingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cc_node::a_operation_landing >::value();
  }
  static const char* value(const ::cc_node::a_operation_landingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cc_node::a_operation_landingRequest> should match 
// service_traits::DataType< ::cc_node::a_operation_landing > 
template<>
struct DataType< ::cc_node::a_operation_landingRequest>
{
  static const char* value()
  {
    return DataType< ::cc_node::a_operation_landing >::value();
  }
  static const char* value(const ::cc_node::a_operation_landingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cc_node::a_operation_landingResponse> should match 
// service_traits::MD5Sum< ::cc_node::a_operation_landing > 
template<>
struct MD5Sum< ::cc_node::a_operation_landingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cc_node::a_operation_landing >::value();
  }
  static const char* value(const ::cc_node::a_operation_landingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cc_node::a_operation_landingResponse> should match 
// service_traits::DataType< ::cc_node::a_operation_landing > 
template<>
struct DataType< ::cc_node::a_operation_landingResponse>
{
  static const char* value()
  {
    return DataType< ::cc_node::a_operation_landing >::value();
  }
  static const char* value(const ::cc_node::a_operation_landingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CC_NODE_MESSAGE_A_OPERATION_LANDING_H
