// Generated by gencpp from file cc_node/a_operation_turn_to_direction.msg
// DO NOT EDIT!


#ifndef CC_NODE_MESSAGE_A_OPERATION_TURN_TO_DIRECTION_H
#define CC_NODE_MESSAGE_A_OPERATION_TURN_TO_DIRECTION_H

#include <ros/service_traits.h>


#include <cc_node/a_operation_turn_to_directionRequest.h>
#include <cc_node/a_operation_turn_to_directionResponse.h>


namespace cc_node
{

struct a_operation_turn_to_direction
{

typedef a_operation_turn_to_directionRequest Request;
typedef a_operation_turn_to_directionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct a_operation_turn_to_direction
} // namespace cc_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cc_node::a_operation_turn_to_direction > {
  static const char* value()
  {
    return "04bfe09b9b370af085e1e4ee62512b6d";
  }

  static const char* value(const ::cc_node::a_operation_turn_to_direction&) { return value(); }
};

template<>
struct DataType< ::cc_node::a_operation_turn_to_direction > {
  static const char* value()
  {
    return "cc_node/a_operation_turn_to_direction";
  }

  static const char* value(const ::cc_node::a_operation_turn_to_direction&) { return value(); }
};


// service_traits::MD5Sum< ::cc_node::a_operation_turn_to_directionRequest> should match 
// service_traits::MD5Sum< ::cc_node::a_operation_turn_to_direction > 
template<>
struct MD5Sum< ::cc_node::a_operation_turn_to_directionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cc_node::a_operation_turn_to_direction >::value();
  }
  static const char* value(const ::cc_node::a_operation_turn_to_directionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cc_node::a_operation_turn_to_directionRequest> should match 
// service_traits::DataType< ::cc_node::a_operation_turn_to_direction > 
template<>
struct DataType< ::cc_node::a_operation_turn_to_directionRequest>
{
  static const char* value()
  {
    return DataType< ::cc_node::a_operation_turn_to_direction >::value();
  }
  static const char* value(const ::cc_node::a_operation_turn_to_directionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cc_node::a_operation_turn_to_directionResponse> should match 
// service_traits::MD5Sum< ::cc_node::a_operation_turn_to_direction > 
template<>
struct MD5Sum< ::cc_node::a_operation_turn_to_directionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cc_node::a_operation_turn_to_direction >::value();
  }
  static const char* value(const ::cc_node::a_operation_turn_to_directionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cc_node::a_operation_turn_to_directionResponse> should match 
// service_traits::DataType< ::cc_node::a_operation_turn_to_direction > 
template<>
struct DataType< ::cc_node::a_operation_turn_to_directionResponse>
{
  static const char* value()
  {
    return DataType< ::cc_node::a_operation_turn_to_direction >::value();
  }
  static const char* value(const ::cc_node::a_operation_turn_to_directionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CC_NODE_MESSAGE_A_OPERATION_TURN_TO_DIRECTION_H
