// Generated by gencpp from file cc_node/a_operation_fly_to_pos.msg
// DO NOT EDIT!


#ifndef CC_NODE_MESSAGE_A_OPERATION_FLY_TO_POS_H
#define CC_NODE_MESSAGE_A_OPERATION_FLY_TO_POS_H

#include <ros/service_traits.h>


#include <cc_node/a_operation_fly_to_posRequest.h>
#include <cc_node/a_operation_fly_to_posResponse.h>


namespace cc_node
{

struct a_operation_fly_to_pos
{

typedef a_operation_fly_to_posRequest Request;
typedef a_operation_fly_to_posResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct a_operation_fly_to_pos
} // namespace cc_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cc_node::a_operation_fly_to_pos > {
  static const char* value()
  {
    return "6d61bc21b7b509c51683fcc6fb95d397";
  }

  static const char* value(const ::cc_node::a_operation_fly_to_pos&) { return value(); }
};

template<>
struct DataType< ::cc_node::a_operation_fly_to_pos > {
  static const char* value()
  {
    return "cc_node/a_operation_fly_to_pos";
  }

  static const char* value(const ::cc_node::a_operation_fly_to_pos&) { return value(); }
};


// service_traits::MD5Sum< ::cc_node::a_operation_fly_to_posRequest> should match 
// service_traits::MD5Sum< ::cc_node::a_operation_fly_to_pos > 
template<>
struct MD5Sum< ::cc_node::a_operation_fly_to_posRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cc_node::a_operation_fly_to_pos >::value();
  }
  static const char* value(const ::cc_node::a_operation_fly_to_posRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cc_node::a_operation_fly_to_posRequest> should match 
// service_traits::DataType< ::cc_node::a_operation_fly_to_pos > 
template<>
struct DataType< ::cc_node::a_operation_fly_to_posRequest>
{
  static const char* value()
  {
    return DataType< ::cc_node::a_operation_fly_to_pos >::value();
  }
  static const char* value(const ::cc_node::a_operation_fly_to_posRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cc_node::a_operation_fly_to_posResponse> should match 
// service_traits::MD5Sum< ::cc_node::a_operation_fly_to_pos > 
template<>
struct MD5Sum< ::cc_node::a_operation_fly_to_posResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cc_node::a_operation_fly_to_pos >::value();
  }
  static const char* value(const ::cc_node::a_operation_fly_to_posResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cc_node::a_operation_fly_to_posResponse> should match 
// service_traits::DataType< ::cc_node::a_operation_fly_to_pos > 
template<>
struct DataType< ::cc_node::a_operation_fly_to_posResponse>
{
  static const char* value()
  {
    return DataType< ::cc_node::a_operation_fly_to_pos >::value();
  }
  static const char* value(const ::cc_node::a_operation_fly_to_posResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CC_NODE_MESSAGE_A_OPERATION_FLY_TO_POS_H
