// Generated by gencpp from file cc_node/conf_statesRequest.msg
// DO NOT EDIT!


#ifndef CC_NODE_MESSAGE_CONF_STATESREQUEST_H
#define CC_NODE_MESSAGE_CONF_STATESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cc_node
{
template <class ContainerAllocator>
struct conf_statesRequest_
{
  typedef conf_statesRequest_<ContainerAllocator> Type;

  conf_statesRequest_()
    : airborne(false)
    , in_mission(false)
    , landing_phase(false)  {
    }
  conf_statesRequest_(const ContainerAllocator& _alloc)
    : airborne(false)
    , in_mission(false)
    , landing_phase(false)  {
  (void)_alloc;
    }



   typedef uint8_t _airborne_type;
  _airborne_type airborne;

   typedef uint8_t _in_mission_type;
  _in_mission_type in_mission;

   typedef uint8_t _landing_phase_type;
  _landing_phase_type landing_phase;





  typedef boost::shared_ptr< ::cc_node::conf_statesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cc_node::conf_statesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct conf_statesRequest_

typedef ::cc_node::conf_statesRequest_<std::allocator<void> > conf_statesRequest;

typedef boost::shared_ptr< ::cc_node::conf_statesRequest > conf_statesRequestPtr;
typedef boost::shared_ptr< ::cc_node::conf_statesRequest const> conf_statesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cc_node::conf_statesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cc_node::conf_statesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cc_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'cc_node': ['/home/pi/airdrop_ros/src/cc_node/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cc_node::conf_statesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cc_node::conf_statesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cc_node::conf_statesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cc_node::conf_statesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cc_node::conf_statesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cc_node::conf_statesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cc_node::conf_statesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1af6d97362fd29242bfa3658b1190ad5";
  }

  static const char* value(const ::cc_node::conf_statesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1af6d97362fd2924ULL;
  static const uint64_t static_value2 = 0x2bfa3658b1190ad5ULL;
};

template<class ContainerAllocator>
struct DataType< ::cc_node::conf_statesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc_node/conf_statesRequest";
  }

  static const char* value(const ::cc_node::conf_statesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cc_node::conf_statesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool airborne\n\
bool in_mission\n\
bool landing_phase\n\
";
  }

  static const char* value(const ::cc_node::conf_statesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cc_node::conf_statesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.airborne);
      stream.next(m.in_mission);
      stream.next(m.landing_phase);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct conf_statesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cc_node::conf_statesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cc_node::conf_statesRequest_<ContainerAllocator>& v)
  {
    s << indent << "airborne: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.airborne);
    s << indent << "in_mission: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.in_mission);
    s << indent << "landing_phase: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.landing_phase);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CC_NODE_MESSAGE_CONF_STATESREQUEST_H
