// Generated by gencpp from file cc_node/conf_states.msg
// DO NOT EDIT!


#ifndef CC_NODE_MESSAGE_CONF_STATES_H
#define CC_NODE_MESSAGE_CONF_STATES_H

#include <ros/service_traits.h>


#include <cc_node/conf_statesRequest.h>
#include <cc_node/conf_statesResponse.h>


namespace cc_node
{

struct conf_states
{

typedef conf_statesRequest Request;
typedef conf_statesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct conf_states
} // namespace cc_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cc_node::conf_states > {
  static const char* value()
  {
    return "41b8919b25873c4fbe3311c2af4f962d";
  }

  static const char* value(const ::cc_node::conf_states&) { return value(); }
};

template<>
struct DataType< ::cc_node::conf_states > {
  static const char* value()
  {
    return "cc_node/conf_states";
  }

  static const char* value(const ::cc_node::conf_states&) { return value(); }
};


// service_traits::MD5Sum< ::cc_node::conf_statesRequest> should match 
// service_traits::MD5Sum< ::cc_node::conf_states > 
template<>
struct MD5Sum< ::cc_node::conf_statesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cc_node::conf_states >::value();
  }
  static const char* value(const ::cc_node::conf_statesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cc_node::conf_statesRequest> should match 
// service_traits::DataType< ::cc_node::conf_states > 
template<>
struct DataType< ::cc_node::conf_statesRequest>
{
  static const char* value()
  {
    return DataType< ::cc_node::conf_states >::value();
  }
  static const char* value(const ::cc_node::conf_statesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cc_node::conf_statesResponse> should match 
// service_traits::MD5Sum< ::cc_node::conf_states > 
template<>
struct MD5Sum< ::cc_node::conf_statesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cc_node::conf_states >::value();
  }
  static const char* value(const ::cc_node::conf_statesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cc_node::conf_statesResponse> should match 
// service_traits::DataType< ::cc_node::conf_states > 
template<>
struct DataType< ::cc_node::conf_statesResponse>
{
  static const char* value()
  {
    return DataType< ::cc_node::conf_states >::value();
  }
  static const char* value(const ::cc_node::conf_statesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CC_NODE_MESSAGE_CONF_STATES_H
