// Generated by gencpp from file cc_node/get_set_take_off_pos.msg
// DO NOT EDIT!


#ifndef CC_NODE_MESSAGE_GET_SET_TAKE_OFF_POS_H
#define CC_NODE_MESSAGE_GET_SET_TAKE_OFF_POS_H

#include <ros/service_traits.h>


#include <cc_node/get_set_take_off_posRequest.h>
#include <cc_node/get_set_take_off_posResponse.h>


namespace cc_node
{

struct get_set_take_off_pos
{

typedef get_set_take_off_posRequest Request;
typedef get_set_take_off_posResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_set_take_off_pos
} // namespace cc_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cc_node::get_set_take_off_pos > {
  static const char* value()
  {
    return "cb8b16d8dc4146dca7889be0392bf192";
  }

  static const char* value(const ::cc_node::get_set_take_off_pos&) { return value(); }
};

template<>
struct DataType< ::cc_node::get_set_take_off_pos > {
  static const char* value()
  {
    return "cc_node/get_set_take_off_pos";
  }

  static const char* value(const ::cc_node::get_set_take_off_pos&) { return value(); }
};


// service_traits::MD5Sum< ::cc_node::get_set_take_off_posRequest> should match 
// service_traits::MD5Sum< ::cc_node::get_set_take_off_pos > 
template<>
struct MD5Sum< ::cc_node::get_set_take_off_posRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cc_node::get_set_take_off_pos >::value();
  }
  static const char* value(const ::cc_node::get_set_take_off_posRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cc_node::get_set_take_off_posRequest> should match 
// service_traits::DataType< ::cc_node::get_set_take_off_pos > 
template<>
struct DataType< ::cc_node::get_set_take_off_posRequest>
{
  static const char* value()
  {
    return DataType< ::cc_node::get_set_take_off_pos >::value();
  }
  static const char* value(const ::cc_node::get_set_take_off_posRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cc_node::get_set_take_off_posResponse> should match 
// service_traits::MD5Sum< ::cc_node::get_set_take_off_pos > 
template<>
struct MD5Sum< ::cc_node::get_set_take_off_posResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cc_node::get_set_take_off_pos >::value();
  }
  static const char* value(const ::cc_node::get_set_take_off_posResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cc_node::get_set_take_off_posResponse> should match 
// service_traits::DataType< ::cc_node::get_set_take_off_pos > 
template<>
struct DataType< ::cc_node::get_set_take_off_posResponse>
{
  static const char* value()
  {
    return DataType< ::cc_node::get_set_take_off_pos >::value();
  }
  static const char* value(const ::cc_node::get_set_take_off_posResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CC_NODE_MESSAGE_GET_SET_TAKE_OFF_POS_H
