// Generated by gencpp from file cc_node/manual_action.msg
// DO NOT EDIT!


#ifndef CC_NODE_MESSAGE_MANUAL_ACTION_H
#define CC_NODE_MESSAGE_MANUAL_ACTION_H

#include <ros/service_traits.h>


#include <cc_node/manual_actionRequest.h>
#include <cc_node/manual_actionResponse.h>


namespace cc_node
{

struct manual_action
{

typedef manual_actionRequest Request;
typedef manual_actionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct manual_action
} // namespace cc_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cc_node::manual_action > {
  static const char* value()
  {
    return "96b258534bcb1e3eb6622e57cbccfdc8";
  }

  static const char* value(const ::cc_node::manual_action&) { return value(); }
};

template<>
struct DataType< ::cc_node::manual_action > {
  static const char* value()
  {
    return "cc_node/manual_action";
  }

  static const char* value(const ::cc_node::manual_action&) { return value(); }
};


// service_traits::MD5Sum< ::cc_node::manual_actionRequest> should match 
// service_traits::MD5Sum< ::cc_node::manual_action > 
template<>
struct MD5Sum< ::cc_node::manual_actionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cc_node::manual_action >::value();
  }
  static const char* value(const ::cc_node::manual_actionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cc_node::manual_actionRequest> should match 
// service_traits::DataType< ::cc_node::manual_action > 
template<>
struct DataType< ::cc_node::manual_actionRequest>
{
  static const char* value()
  {
    return DataType< ::cc_node::manual_action >::value();
  }
  static const char* value(const ::cc_node::manual_actionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cc_node::manual_actionResponse> should match 
// service_traits::MD5Sum< ::cc_node::manual_action > 
template<>
struct MD5Sum< ::cc_node::manual_actionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cc_node::manual_action >::value();
  }
  static const char* value(const ::cc_node::manual_actionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cc_node::manual_actionResponse> should match 
// service_traits::DataType< ::cc_node::manual_action > 
template<>
struct DataType< ::cc_node::manual_actionResponse>
{
  static const char* value()
  {
    return DataType< ::cc_node::manual_action >::value();
  }
  static const char* value(const ::cc_node::manual_actionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CC_NODE_MESSAGE_MANUAL_ACTION_H
