// Generated by gencpp from file battery_node/bat_stat.msg
// DO NOT EDIT!


#ifndef BATTERY_NODE_MESSAGE_BAT_STAT_H
#define BATTERY_NODE_MESSAGE_BAT_STAT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace battery_node
{
template <class ContainerAllocator>
struct bat_stat_
{
  typedef bat_stat_<ContainerAllocator> Type;

  bat_stat_()
    : bat_val(0)  {
    }
  bat_stat_(const ContainerAllocator& _alloc)
    : bat_val(0)  {
  (void)_alloc;
    }



   typedef int32_t _bat_val_type;
  _bat_val_type bat_val;





  typedef boost::shared_ptr< ::battery_node::bat_stat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::battery_node::bat_stat_<ContainerAllocator> const> ConstPtr;

}; // struct bat_stat_

typedef ::battery_node::bat_stat_<std::allocator<void> > bat_stat;

typedef boost::shared_ptr< ::battery_node::bat_stat > bat_statPtr;
typedef boost::shared_ptr< ::battery_node::bat_stat const> bat_statConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::battery_node::bat_stat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::battery_node::bat_stat_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace battery_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'battery_node': ['/home/pi/airdrop_ros/src/battery_node/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::battery_node::bat_stat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::battery_node::bat_stat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::battery_node::bat_stat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::battery_node::bat_stat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::battery_node::bat_stat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::battery_node::bat_stat_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::battery_node::bat_stat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6362255f22432ff23dbe6f399bfa3970";
  }

  static const char* value(const ::battery_node::bat_stat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6362255f22432ff2ULL;
  static const uint64_t static_value2 = 0x3dbe6f399bfa3970ULL;
};

template<class ContainerAllocator>
struct DataType< ::battery_node::bat_stat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "battery_node/bat_stat";
  }

  static const char* value(const ::battery_node::bat_stat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::battery_node::bat_stat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 bat_val\n\
";
  }

  static const char* value(const ::battery_node::bat_stat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::battery_node::bat_stat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bat_val);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bat_stat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::battery_node::bat_stat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::battery_node::bat_stat_<ContainerAllocator>& v)
  {
    s << indent << "bat_val: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bat_val);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BATTERY_NODE_MESSAGE_BAT_STAT_H
