// Generated by gencpp from file mission_node/list_missionsResponse.msg
// DO NOT EDIT!


#ifndef MISSION_NODE_MESSAGE_LIST_MISSIONSRESPONSE_H
#define MISSION_NODE_MESSAGE_LIST_MISSIONSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mission_node
{
template <class ContainerAllocator>
struct list_missionsResponse_
{
  typedef list_missionsResponse_<ContainerAllocator> Type;

  list_missionsResponse_()
    : mission_list()  {
    }
  list_missionsResponse_(const ContainerAllocator& _alloc)
    : mission_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _mission_list_type;
  _mission_list_type mission_list;





  typedef boost::shared_ptr< ::mission_node::list_missionsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mission_node::list_missionsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct list_missionsResponse_

typedef ::mission_node::list_missionsResponse_<std::allocator<void> > list_missionsResponse;

typedef boost::shared_ptr< ::mission_node::list_missionsResponse > list_missionsResponsePtr;
typedef boost::shared_ptr< ::mission_node::list_missionsResponse const> list_missionsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mission_node::list_missionsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mission_node::list_missionsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mission_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mission_node::list_missionsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mission_node::list_missionsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mission_node::list_missionsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mission_node::list_missionsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mission_node::list_missionsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mission_node::list_missionsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mission_node::list_missionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d952d9b438834ab872583b9374911ec";
  }

  static const char* value(const ::mission_node::list_missionsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d952d9b438834abULL;
  static const uint64_t static_value2 = 0x872583b9374911ecULL;
};

template<class ContainerAllocator>
struct DataType< ::mission_node::list_missionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mission_node/list_missionsResponse";
  }

  static const char* value(const ::mission_node::list_missionsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mission_node::list_missionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] mission_list\n\
\n\
";
  }

  static const char* value(const ::mission_node::list_missionsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mission_node::list_missionsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mission_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct list_missionsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mission_node::list_missionsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mission_node::list_missionsResponse_<ContainerAllocator>& v)
  {
    s << indent << "mission_list[]" << std::endl;
    for (size_t i = 0; i < v.mission_list.size(); ++i)
    {
      s << indent << "  mission_list[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mission_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MISSION_NODE_MESSAGE_LIST_MISSIONSRESPONSE_H
