// Generated by gencpp from file mission_node/start_missionRequest.msg
// DO NOT EDIT!


#ifndef MISSION_NODE_MESSAGE_START_MISSIONREQUEST_H
#define MISSION_NODE_MESSAGE_START_MISSIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mission_node
{
template <class ContainerAllocator>
struct start_missionRequest_
{
  typedef start_missionRequest_<ContainerAllocator> Type;

  start_missionRequest_()
    : mission_name()  {
    }
  start_missionRequest_(const ContainerAllocator& _alloc)
    : mission_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mission_name_type;
  _mission_name_type mission_name;





  typedef boost::shared_ptr< ::mission_node::start_missionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mission_node::start_missionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct start_missionRequest_

typedef ::mission_node::start_missionRequest_<std::allocator<void> > start_missionRequest;

typedef boost::shared_ptr< ::mission_node::start_missionRequest > start_missionRequestPtr;
typedef boost::shared_ptr< ::mission_node::start_missionRequest const> start_missionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mission_node::start_missionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mission_node::start_missionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mission_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mission_node::start_missionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mission_node::start_missionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mission_node::start_missionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mission_node::start_missionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mission_node::start_missionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mission_node::start_missionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mission_node::start_missionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58d2a351cca0e183374ddcd0f9020808";
  }

  static const char* value(const ::mission_node::start_missionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58d2a351cca0e183ULL;
  static const uint64_t static_value2 = 0x374ddcd0f9020808ULL;
};

template<class ContainerAllocator>
struct DataType< ::mission_node::start_missionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mission_node/start_missionRequest";
  }

  static const char* value(const ::mission_node::start_missionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mission_node::start_missionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mission_name\n\
";
  }

  static const char* value(const ::mission_node::start_missionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mission_node::start_missionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mission_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct start_missionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mission_node::start_missionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mission_node::start_missionRequest_<ContainerAllocator>& v)
  {
    s << indent << "mission_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mission_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MISSION_NODE_MESSAGE_START_MISSIONREQUEST_H
